# Generated by Django 5.0.6 on 2024-08-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChaiVariety',
        ),
    ]
